version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres
 
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres
    depends_on:
      - postgres

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./rabbitmq.env

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    env_file:
      - ./apps/auth/.env
    depends_on:
      - rabbitmq
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '5000:5000'

  aws:
    build:
      context: .
      dockerfile: ./apps/aws/Dockerfile
      target: development
    command: npm run start:dev aws
    env_file:
      - ./apps/aws/.env
    depends_on:
      - rabbitmq
      - auth
      - parts
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  car:
    build:
      context: .
      dockerfile: ./apps/car/Dockerfile
      target: development
    command: npm run start:dev car
    env_file:
      - ./apps/car/.env
    depends_on:
      - rabbitmq
      - auth
      - parts
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  car-service:
    build:
      context: .
      dockerfile: ./apps/car-service/Dockerfile
      target: development
    command: npm run start:dev car-service
    env_file:
      - ./apps/car-service/.env
    depends_on:
      - rabbitmq
      - auth
      - car
      - parts
      - aws
      - chat-gpt
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  chat-gpt:
    build:
      context: .
      dockerfile: ./apps/chat-gpt/Dockerfile
      target: development
    command: npm run start:dev chat-gpt
    env_file:
      - ./apps/chat-gpt/.env
    depends_on:
      - rabbitmq
      - auth
      - car
      - parts
      - aws
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  parts:
    build:
      context: .
      dockerfile: ./apps/parts/Dockerfile
      target: development
    command: npm run start:dev parts
    env_file:
      - ./apps/parts/.env
    depends_on:
      - rabbitmq
      - auth
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

networks:
  postgres:
    driver: bridge
